import nltk
nltk.download('maxent_ne_chunker_tab')

defined_video_categories = [
    "Film & Movies",
    "Cars",
    "Music",
    "Lifestyle",
    "Finance",
    "Education",
    "Science & Technology",
    "Entertainment",
    "News & Politics",
    "Sports",
    "Gaming",
    "Howto & Style"
]

# Model data 82.16% accuracy
training_data = [
    ("Star Wars Rise of Skywalker 2020 Official Trailer", "Film & Movies"),
    ("The Substance, thoughts and opinions", "Film & Movies"),
    ("Joker 2019 Movie Review", "Film & Movies"),
    ("Top 10 Fastest Cars in the World", "Cars"),
    ("Tesla Model X Test Drive and Review", "Cars"),
    ("Lamborghini Huracan Performante Review", "Cars"),
    ("Top 10 Music Hits of the Year", "Music"),
    ("Best Music Festivals of 2020", "Music"),
    ("Billie Eilish Live Concert", "Music"),
    ("10 Tips for a Healthy Lifestyle", "Lifestyle"),
    ("Travel Vlog: Bali 2020", "Lifestyle"),
    ("Minimalist Living Guide", "Lifestyle"),
    ("How to plan out the best study routine", "Education"),
    ("Top 10 Universities in the World", "Education"),
    ("Learn to Code in Python", "Education"),
    ("New discoveries in quantum physics", "Science & Technology"),
    ("The latest in AI and Machine Learning", "Science & Technology"),
    ("SpaceX Launch Live", "Science & Technology"),
    ("Funny cat videos compilation", "Entertainment"),
    ("The best comedy shows of the year", "Entertainment"),
    ("Stand-up Comedy Special: John Mulaney", "Entertainment"),
    ("Breaking News: Major Election Updates", "News & Politics"),
    ("The latest in global politics", "News & Politics"),
    ("Documentary: The History of Democracy", "News & Politics"),
    ("Top 10 Goals of the Year", "Sports"),
    ("The best sports moments of the year", "Sports"),
    ("Monaco Grand Prix 2020 Highlights", "Sports"),
    ("The best gameplay tips for Call of Duty", "Gaming"),
    ("Top 10 Games of the Year", "Gaming"),
    ("Let's Play: The Last of Us Part II", "Gaming"),
    ("How to do the perfect winged eyeliner", "Howto & Style"),
    ("The latest fashion trends of 2020", "Howto & Style"),
    ("DIY Home Decor Projects", "Howto & Style"),
    ("The best financial advice for 2020", "Finance"),
    ("How to invest in the stock market", "Finance"),
    ("Budgeting 101: A Beginner's Guide", "Finance"),
    ("How to do the perfect winged eyeliner", "Howto & Style"),
    ("The latest fashion trends of 2020", "Howto & Style"),
    ("How to plan out the best study routine", "Education"),
    ("Top 10 Music Hits of the Year", "Music"),
    ("Breaking News: Major Election Updates", "News & Politics"),
    ("New discoveries in quantum physics", "Science & Technology"),
    ("Funny cat videos compilation", "Entertainment"),
    ("The best gameplay tips for Call of Duty", "Gaming"),
    ("Top 10 Movies of 2019", "Film & Movies"),
    ("Car Crash Compilation", "Cars"), 
    ("Jazz Music Playlist 2020", "Music"),
    ("Vegan Recipes for Beginners", "Lifestyle"),
    ("Online Learning Platforms for Students", "Education"), 
    ("The Future of Space Exploration", "Science & Technology"),
    ("Stand-up Comedy Highlights", "Entertainment"),
    ("Political Debates 2020", "News & Politics"),
    ("Soccer World Cup Highlights", "Sports"), 
    ("Gaming Tips and Tricks", "Gaming"),
    ("Fashion Show Highlights 2020", "Howto & Style"),
    ("Investing in Real Estate", "Finance"),
    ("Documentary: The Making of Star Wars", "Film & Movies"),
    ("Electric Car Reviews", "Cars"),
    ("Top 10 Pop Songs 2020", "Music"),
    ("Travel Guide: New York City", "Lifestyle"),
    ("Learn a New Language: Spanish", "Education"),
    ("Artificial Intelligence Explained", "Science & Technology"),
    ("Funny Animal Videos", "Entertainment"),
    ("Presidential Elections 2020", "News & Politics"),
    ("Olympic Games 2020 Highlights", "Sports"),
    ("Gaming Tournaments 2020", "Gaming"),
    ("Makeup Tutorials for Beginners", "Howto & Style"),
    ("Personal Finance 101", "Finance"),
    ("The Lord of the Rings Trilogy", "Film & Movies"),
    ("Car Maintenance Tips", "Cars"),
    ("Music Videos 2020", "Music"),
    ("Healthy Eating Habits", "Lifestyle"),
    ("Online Courses: Learn Anything", "Education"),
    ("Technology of the Future", "Science & Technology"),
    ("Magic Tricks and Illusions", "Entertainment"),
    ("Political Scandals", "News & Politics"),
    ("NBA Finals Highlights", "Sports"),
    ("Top 10 Mobile Games", "Gaming"),
    ("Fashion Trends 2020", "Howto & Style"),
    ("Cryptocurrency Explained", "Finance"),
    ("The Hobbit Trilogy", "Film & Movies"),
    ("Top Gear: Best Episodes", "Cars"),
    ("Top 10 Rock Songs 2020", "Music"),
    ("Healthy Living Tips", "Lifestyle"),
    ("Study Tips for Students", "Education"),
    ("The Science of Black Holes", "Science & Technology"),
    ("Comedy Shows 2020", "Entertainment"),
    ("Global News Updates", "News & Politics"),
    ("NFL Season Highlights", "Sports"),
    ("Best PC Games of 2020", "Gaming"),
    ("Makeup Tips and Tricks", "Howto & Style"),
    ("Personal Budgeting Strategies", "Finance"),
    ("Harry Potter Movie Marathon", "Film & Movies"),
    ("Car Racing Highlights", "Cars"),
    ("Top 10 Indie Songs 2020", "Music"),
    ("Healthy Breakfast Recipes", "Lifestyle"),
    ("History Documentaries", "Education"),
    ("The Future of Robotics", "Science & Technology"),
    ("Funny TikTok Videos", "Entertainment"),
    ("Election Coverage 2020", "News & Politics"),
    ("MLB Season Highlights", "Sports"),
    ("Best Mobile Games of 2020", "Gaming"),
    ("Fashion Tips and Tricks", "Howto & Style"),
    ("Stock Market Strategies", "Finance"),
    ("The Matrix Trilogy", "Film & Movies"),
    ("Car Reviews 2020", "Cars"),
    ("Top 10 Rap Songs 2020", "Music"),
    ("Healthy Dinner Recipes", "Lifestyle"),
    ("Online Learning Platforms for Professionals", "Education"),
    ("The Future of Medicine", "Science & Technology"),
    ("Funny Dog Videos", "Entertainment"),
    ("Global Politics Updates", "News & Politics"),
    ("NHL Season Highlights", "Sports"),
    ("Best Console Games of 2020", "Gaming"),
    ("Skincare Tips and Tricks", "Howto & Style"),
    ("Investing in Cryptocurrency", "Finance"),
    ("Star Trek Movie Marathon", "Film & Movies"),
    ("Car Crash Compilation", "Cars"),
    ("Top 10 EDM Songs 2020", "Music"),
    ("Healthy Snack Recipes", "Lifestyle"),
    ("Online Learning Platforms for Kids", "Education"),
    ("The Future of Renewable Energy", "Science & Technology"),
    ("Funny Animal Videos", "Entertainment"),
    ("Global News Updates", "News & Politics"),
    ("NBA Finals Highlights", "Sports"),
    ("Best PC Games of 2020", "Gaming"),
    ("Makeup Tips and Tricks", "Howto & Style"),
    ("Personal Budgeting Strategies", "Finance"),
    ("Harry Potter Movie Marathon", "Film & Movies"),
    ("Car Racing Highlights", "Cars"),
    ("Top 10 Indie Songs 2020", "Music"),
    ("Healthy Breakfast Recipes", "Lifestyle"),
    ("History Documentaries", "Education"),
    ("The Future of Robotics", "Science & Technology"),
    # ("Upbeat Playlist 2021", "Music"),
    # ("The technology behind Unsupervised systems", "Science & Technology"),
    # ("how to study the web ?", "Education")
    # ("How to get started with writing code", "Education"),
    # ("Upbeat temo Mashup", "Music"),
#     ("What is Money Laundering", "Finance"),
#     ("What is Blockchain Technology", "Education"),
#     ("The Red Light district why the netherlands is investing in tourism", "Education"),  
]